# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
